### ISSUE TITLE
Rework Fun Pool

### ISSUE THREAD

**Issue by technodono** [OvercastCommunity/MapPools#9]
this comes from this comment: https://github.com/OvercastCommunity/MapPools/commit/1dadb015ff2dd4fa78a63dd83396bec86f405148#commitcomment-52939824

Crazy suggested that we load some of the maps that don't fit in SNS into the fun pool as part of a "pool rework"

@CoWinkKeyDinkInc has offered to do this... so I though I'd make an issue about it here in-case any other mapmakers wanna contribute to this new pool and also to give my thoughts on the possible maps for this pool:

### Possible new maps:

- race circuit, pebble creek, ender e.c.t

- pixel run, the history run, rush wars 2: attack of torrment... e.c.t.

- cannonquad + & cannonduel

- cos(tnt), beach battles, checkmate, boombox, bomberguys (maybe PE can fix too!), csct(tnt), cos^2(tnt), library, databasin, DATAstation, Cannon Cube, Ender Cube e.c.t.

- sand wars DTE and sandwars invsipearl bow koth EXtreme

- Ballot box

- Blockglitch

- Zipline moar gunz & Diretrix moar guns

- Medieival warfare

- 101 roooms (Rage version)

- Hide 'n' seek (origonal)

- juggernauts hall

- Water drop extreme, Water drop: sunrise, limbo II e.c.t

- the hopper?

- The dropper & dropper CE

- team parkour jungle, ice... e.c.t

- tnt spleef, maybe even tnt rain (if it stops lagging out the server to hell)

- ladderp II

### Maps to remove:

- Ozone (huge map... won't suit most player counts)

- Sand wars: the DTE version is much more fun

- Spaceship battles: the map can take a while and has 3 different objectives... if defended map can easily stalemate

- RFV: wool maps can take 2hr... not very happy

- The nile: 2hr matches are annoying... the infection version is better

- fortress battles: it's real easy to defend that core in OP ways that makes matches long & stale or immediately win from team not defending

- Equinox... 2 HIll CTP's aren't exactly fun or competitive and the maps always played... it's not like that fun I find

- astrogen... basically for the same reasons that RFV isn't in pools

- 101 rooms TDM: I think the rage version is just a lil more fun even if it is rage

- desert sanctuary.. it's just a regular KoTF... and is also overplayed a fair bit... I personally don't wanna see it in the pools but yea

**Comment by CoWinkKeyDinkInc** [comment]
So the idea here is that the `fun` pool will be for longer fun maps that otherwise would not fit into the `sns` pool. Or this can become a new pool.

101 Rooms TDM, water drop sunrise, ladderp ii are good additions. I think Ballot Box was recently removed but it's good to know that there are people that really enjoyed that map.

> fortress battles: it's real easy to defend that core in OP ways that makes matches long & stale or immediately win from team not defending

Same could be said about Medieval Warfare, unless you're talking about the DTE version? That should be added. Other than my other comments and Sand Wars, I agree with the rest of what you want removed. I'm going to be away this week so I'll look at all the maps and write something up.

**Comment by technodono** [comment]
> 
> 
> So the idea here is that the `fun` pool will be for longer fun maps that otherwise would not fit into the `sns` pool. Or this can become a new pool.
> 
> 101 Rooms TDM, water drop sunrise, ladderp ii are good additions. I think Ballot Box was recently removed but it's good to know that there are people that really enjoyed that map.
> 
> > fortress battles: it's real easy to defend that core in OP ways that makes matches long & stale or immediately win from team not defending
> 
> Same could be said about Medieval Warfare, unless you're talking about the DTE version? That should be added. Other than my other comments and Sand Wars, I agree with the rest of what you want removed. I'm going to be away this week so I'll look at all the maps and write something up.

yes Medieval DTE...

**Comment by Omote23** [comment]
I don't think the nile is annoying. actually I think the Nile is the most tactical-required map. you have to make an armor stand to reduce fillup time. handling skybridge, rushing, making a house, or doing weird stuff (making power 3+ bow or something).

**Comment by technodono** [comment]
> 
> 
> I don't think the nile is annoying. actually I think the Nile is the most tactical-required map. you have to make an armor stand to reduce fillup time. handling skybridge, rushing, making a house, or doing weird stuff (making power 3+ bow or something).

it's not about it being annoying... it's just about how long the map takes... I don't want any maps in this pool to go above 2hr and nile has been known to stalemate hence why I vote to remove it from the pool

**Comment by Omote23** [comment]
hmm... then, maybe we need a stalemate pool for the players who love the long match.

**Comment by technodono** [comment]
> 
> 
> hmm... then, maybe we need a stalemate pool for the players who love the long match

Alot of players don't enjoy long matches because the server only really has 1 map on at a time unless the 2nd fallback server is open... let alone if we had such a pool it'd take forever to even try fitting in anything above 3 maps due to the ~1hr each map would take. But I mean if you liek long matches you could get sponsor rank and do things that way

**Comment by calcastor** [comment]
> hmm... then, maybe we need a stalemate pool for the players who love the long match.

This is not a pool that we will be making.

**Comment by calcastor** [comment]
The `fun` pools has been something I've wanted to redo for a while now; from what I can tell it was made somewhat early on in OCC's existence, prior to the `sns` pool. The vast majority of the maps within the pool are already in standard pools, with the few that aren't still somewhat fitting with what you've suggested here.

**Comment by CrazyisCreeps** [comment]
> > hmm... then, maybe we need a stalemate pool for the players who love the long match.
> 
> This is not a pool that we will be making.

Watch me

**Comment by calcastor** [comment]
> > > hmm... then, maybe we need a stalemate pool for the players who love the long match.
> > 
> > 
> > This is not a pool that we will be making.
> 
> Watch me

```yaml
stalemate:
    enabled: false
```

**Comment by CrazyisCreeps** [comment]
> > > > hmm... then, maybe we need a stalemate pool for the players who love the long match.
> > > 
> > > 
> > > This is not a pool that we will be making.
> > 
> > 
> > Watch me
> 
> ```yaml
> stalemate:
>     enabled: false
> ```

ahahaha 😆

**Comment by Omote23** [comment]
Anyways, what is the purpose of "fun" pools?.  I think that the standard of "fun" is really different for each player. 
moreover, I don't know when that "fun" pool activates on OCC. It is activated by staff only?.

**Comment by CrazyisCreeps** [comment]
> Anyways, what is the purpose of "fun" pools?. I think that the standard of "fun" is really different for each player.
> moreover, I don't know when that "fun" pool activates on OCC. It is activated by staff only?.

Yea it's a pool that can only be toggled by staff, much like the sns pool. It really can be called anything, "fun" is just nice and simple (although yea, the normal pools are also fun!)

**Comment by technodono** [comment]
> 
> 
> Anyways, what is the purpose of "fun" pools?. I think that the standard of "fun" is really different for each player.
> moreover, I don't know when that "fun" pool activates on OCC. It is activated by staff only?.

My definition of fun will vary from yours... right now from what I can tell the general census of people do love TNT and I agree with them... what I posted isn't an exact representation of fun... but I mean if more maps come up then more can go into the fun pool... RN it'll act just like crazy's sns pool but the types of maps you'll play are drastically different

**Comment by CoWinkKeyDinkInc** [comment]
I've done a bit of research and here are my considerations. The SNS pool will be shorter maps that cycle quickly, while the fun pool is for maps that last longer but are in the same spirit as maps in the sns pool. 

# Remove from Fun 
- SSB
- Sandwars -> Sandwars DTE
- Ozone
- The Nile
- cos(tnt)
- Concourse

# Move these maps in sns to fun
- Some race maps
- The Dropper
- The Dropper CE

# Add to fun

- Waterdrop sunrise 
- Medieval Warefare DTE
- DATAbasin (tnt dam)
- DATAbase
- DATAcenter
- DATAstation
- the other data map with the small sails (adjust for player size)
- Blocks DTE
- Ballot Box
- Ladderp II
- Banana Split
- the other ladderp maps
- BlitzMiners
- BoomBox
- BoomBoxx
- CannonQuad (BASED MAP)
- DK Crossovers DTE
- Fairy Tales
- Hide n' Seek
- Ieatshall
- Mega Cacti Terror
- Mini Drought
- Rage Quit TDM
- Barfbox
- Sky Traffic
- Stop the Boats

# Maps to consider/lookup

- 5man
- Ternio
- Yellowstone
- Zen
- Wool Story Bro
- puddin pops
- Bounce
- Bouncy Stadium
- Paint Can't Wait
- Portal
- Pumpkin Spice Latte
- Sand Wall
- The Dome

Not sure if these maps are special or good, but if anyone knows their opinion of them that would be great to hear

**Comment by CoWinkKeyDinkInc** [comment]
Oh yes Ender Blast and CannonCube would be a good addition

**Comment by CrazyisCreeps** [comment]
Yellowstone is def just a lame avicus dtm btw. Also pretty sure Ternio is avicus as well, I just can't remember much about it in terms of gameplay quality 

Oh and also Bounce is just a jump pad with rage and a million arrows. Really not that great, I had it in sns for a bit until it got old real fast

**Comment by technodono** [comment]
> Sand Wall

Rip zipline gunz map... I'm assuming you just forgot lol

also if your going to do the tnt maps defo look into beach battles

**Comment by CoWinkKeyDinkInc** [comment]
Beach Battles is good, I didn't know people liked the Zipline gunz map considering we removed Directrex with Gunz sometime before

**Comment by technodono** [comment]
> Beach Battles is good, I didn't know people liked the Zipline gunz map considering we removed Directrix with Gunz sometime before

the only reason crazy removed it form the pool is bc the map took too long hence the discussion for a new map pool. Considering it was voted alot I think it's safe to have it in... but you'll need to test it in the pools and see if people find it fun.

I think with directrix also, having it rage made it not fun. the guns there have alot of range and it's very hard to see the bullets so you die in weird ways due to ping and other oddities... it just feels kinda hit or miss compared to zip gunz where you do have a chance to survive... one note is that the projectiles launcher can be broken easily by like spam clikcers n stuff somehow circumventing the cool-down it's happened in multiple matches and may need to be investigated???

**Comment by calcastor** [comment]
> Beach Battles is good, I didn't know people liked the Zipline gunz map considering we removed Directrex with Gunz sometime before

It was mostly unloaded because it's based on a far older version of the map and I'm going to add it back in the near future based on the newest version (not that it was very fun either way in comparison to Zipline's somewhat similar version). Zipline Gunz being removed from SNS due to match length was part of the reason this issue was made.

**Comment by CoWinkKeyDinkInc** [comment]
-  5man - 5 player map lol, should've seen it coming
-   Ternio - Avicus lookin map
-    Yellowstone - Crazy was kinda right
-    Zen - 16v16 blitz rage map
-    Wool Story Bro - Kinda like Paint Can't Wait
-    puddin pops - Seems interesting enoungh to me
-    Bouncy Stadium - This map played ok for me but the area might be confusing for new players, seems intersting enoungh to be added though,
-    Paint Can't Wait - Definately should be added now that I remember what this is
-    Portal - Pretty small, I don't really get this map
-    Pumpkin Spice Latte - Only has 16 players but I think it might play well.
-    Sand Wall - Not an interesting blitz rage map
-    The Dome - Blitz Rage map with 32 players, could be adapted for a rage TDM

**Comment by CoWinkKeyDinkInc** [comment]
Out of these I would add Puddin Pops, Wool Story Bro, paint can't wait, Bouncy Stadium, Pumpkin Spice Latte and The Dome

**Comment by technodono** [comment]
> 
> 
> Out of these I would add Puddin Pops, Wool Story Bro, paint can't wait, Bouncy Stadium, Pumpkin Spice Latte and The Dome

looking back, I think it'd definitely be worth it to look into getting bomber guys into this pool too... I think it fits very well

**Comment by CoWinkKeyDinkInc** [comment]
I took this too seriously but now I have brought a breath of fresh air into the fun map pool in 25efd09. Some maps are on both pools, doesn't have to be exactly clear cut, this commit should show my vision.
